"""Regenerate the `pixel` theme's art.

    python3 _pixel/build.py

Writes
  assets/img/pixel/about-<key>.png   the eight album pictures, 112 x 84, screen tones
  assets/img/pixel/perch.png         the birds on the header wire, in their own colours
  assets/img/pixel/perch.svg         the same pixels as vector shapes, for the header
  assets/js/perch-birds.js          individual birds and row bounds for random packing
  _sass/pixel/_sprites.scss          one-tone sprites as SVG mask data URIs,
                                     plus the wire strip's size
  assets/img/pixel/book-cover.png    the book cover as a thermal print (needs ImageMagick)

After regenerating the cover, re-embed its origin:
  impeccable embed-prompt assets/img/pixel/book-cover.png --prompt "<origin>"
"""
import os
import json
import shutil
import subprocess
import tempfile
from urllib.parse import quote

from paint import hexrgb, write_png, write_png_rgba
from scenes import SCENES, W, H
from sprites import all_masks, svg
import wire

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Screen and paper tones, as in _sass/pixel/_tokens.scss
SCREEN_TONES = ["#0c1714", "#1f3a33", "#4f8f7a", "#a8e3c7"]
PRINT_TONES = ["#151816", "#4f544f", "#a9ada7"]
PAPER = "#d6d9d3"


def build_pictures():
    """The album pictures, one PNG each, at one image pixel per picture pixel;
    the page scales them up with nearest-neighbour."""
    out = []
    for name, fn in SCENES:
        path = os.path.join(ROOT, "assets", "img", "pixel", "about-%s.png" % name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        write_png(path, fn(), [hexrgb(h) for h in SCREEN_TONES])
        out.append(path)
    return out


def build_perch():
    """The wire strip, one image pixel per sprite pixel, each bird in its own
    palette, clear where no bird is. Kept as a raster reference; the header
    uses the matching SVG to avoid browser bitmap interpolation."""
    grid, _, _ = wire.strip()
    pixels = [[(0, 0, 0, 0) if c is None else hexrgb(c) + (255,) for c in row] for row in grid]
    path = os.path.join(ROOT, "assets", "img", "pixel", "perch.png")
    write_png_rgba(path, len(grid[0]), len(grid), pixels)
    return path


def pixel_paths(grid):
    """Integer-aligned horizontal runs, grouped by colour."""
    paths = {}
    for y, row in enumerate(grid):
        x = 0
        while x < len(row):
            colour = row[x]
            end = x + 1
            while end < len(row) and row[end] == colour:
                end += 1
            if colour is not None:
                width = end - x
                paths.setdefault(colour, []).append(
                    "M%d %dh%dv1h-%dz" % (x, y, width, width))
            x = end
    return {colour: "".join(runs) for colour, runs in paths.items()}


def build_perch_svg():
    """A static fallback when the random flock script cannot run."""
    grid, _, _ = wire.strip()
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
        'viewBox="0 0 %d %d" shape-rendering="crispEdges">' %
        (len(grid[0]), len(grid), len(grid[0]), len(grid)),
    ]
    lines += ['<path fill="%s" d="%s"/>' % (colour, path)
              for colour, path in pixel_paths(grid).items()]
    lines.append('</svg>')
    path = os.path.join(ROOT, "assets", "img", "pixel", "perch.svg")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def build_perch_birds():
    """Individual SVG paths and row bounds for tightly packing any order."""
    strip, above, _ = wire.strip()
    birds = []
    for name, (rows, wire_row, palette) in wire.BIRDS.items():
        width = len(rows[0])
        grid = [[None] * width for _ in strip]
        for y, row in enumerate(rows):
            for x, colour in enumerate(row):
                if colour not in '. ':
                    grid[above - wire_row + y][x] = palette[colour]
        edges = []
        for row in grid:
            occupied = [x for x, colour in enumerate(row) if colour is not None]
            edges.append([min(occupied), max(occupied)] if occupied else None)
        birds.append(dict(name=name, width=width, paths=pixel_paths(grid), edges=edges))
    path = os.path.join(ROOT, 'assets', 'js', 'perch-birds.js')
    with open(path, 'w') as f:
        f.write('// Generated by _pixel/build.py; edit _pixel/wire.py.\n')
        f.write('export const height = %d;\n' % len(strip))
        f.write('export const gap = %d;\n' % wire.GAP)
        f.write('export const birds = %s;\n' % json.dumps(birds, separators=(',', ':')))
    return path


def build_masks():
    lines = [
        "// Generated by _pixel/build.py — edit _pixel/sprites.py, not this file.",
        "// One-tone pixel sprites, used as CSS masks and coloured by the theme tokens.",
        "",
    ]
    for name, rows in all_masks().items():
        doc, w, h = svg(rows)
        uri = "data:image/svg+xml," + quote(doc, safe=" /:='.,-")
        lines.append("$px-%s: url(\"%s\");" % (name, uri))
        lines.append("$px-%s-w: %d;" % (name, w))
        lines.append("$px-%s-h: %d;" % (name, h))
    grid, _, below = wire.strip()
    lines += [
        "",
        "// The wire strip (assets/img/pixel/perch.svg, _pixel/wire.py)",
        "$perch-w: %d;" % len(grid[0]),
        "$perch-h: %d;" % len(grid),
        "$perch-below: %d;  // rows under the wire, where tails hang" % below,
    ]
    path = os.path.join(ROOT, "_sass", "pixel", "_sprites.scss")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def build_cover(width=224):
    """Print the book cover in the paper's three inks, error-diffused at two
    print dots per CSS pixel (shown at 112 px wide), so the title stays
    legible. The lightest greys are lifted first so the cover's thin line art
    survives. Paper is left transparent."""
    src = os.path.join(ROOT, "_pixel", "src", "book-cover.jpg")
    if not (os.path.exists(src) and shutil.which("magick")):
        return None
    out = os.path.join(ROOT, "assets", "img", "pixel", "book-cover.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        palette = os.path.join(tmp, "inks.png")
        subprocess.run(["magick", "-size", "1x1"] +
                       ["xc:%s" % c for c in PRINT_TONES + [PAPER]] +
                       ["+append", palette], check=True)
        subprocess.run(
            ["magick", src, "-colorspace", "Gray", "-resize", "%dx" % width,
             "-level", "0%,97%,0.3", "-unsharp", "0x0.8+1.0+0", "-colorspace", "sRGB",
             "-dither", "FloydSteinberg", "-remap", palette,
             "-transparent", PAPER, "-strip", out],
            check=True)
    return out


if __name__ == "__main__":
    print("\n".join(build_pictures()))
    print(build_perch())
    print(build_perch_svg())
    print(build_perch_birds())
    print(build_masks())
    print(build_cover())
