"""Regenerate the `pixel` theme's art.

    python3 _pixel/build.py

Writes
  assets/img/pixel/about-<key>.png   the eight album pictures, 112 x 84, screen tones
  assets/img/pixel/perch.png         the birds on the header wire, in their own colours
  _sass/pixel/_sprites.scss          one-tone sprites as SVG mask data URIs,
                                     plus the wire strip's size
  assets/img/pixel/book-cover.png    the book cover as a thermal print (needs ImageMagick)

After regenerating the cover, re-embed its origin:
  impeccable embed-prompt assets/img/pixel/book-cover.png --prompt "<origin>"
"""
import os
import shutil
import subprocess
import tempfile
from urllib.parse import quote

from paint import hexrgb, write_png, write_png_rgba
from scenes import SCENES, W, H
from sprites import all_masks, svg
import wire

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Screen and paper tones, as in _sass/pixel/_tokens.scss
SCREEN_TONES = ["#0c1714", "#1f3a33", "#4f8f7a", "#a8e3c7"]
PRINT_TONES = ["#151816", "#4f544f", "#a9ada7"]
PAPER = "#d6d9d3"


def build_pictures():
    """The album pictures, one PNG each, at one image pixel per picture pixel;
    the page scales them up with nearest-neighbour."""
    out = []
    for name, fn in SCENES:
        path = os.path.join(ROOT, "assets", "img", "pixel", "about-%s.png" % name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        write_png(path, fn(), [hexrgb(h) for h in SCREEN_TONES])
        out.append(path)
    return out


def build_perch():
    """The wire strip, one image pixel per sprite pixel, each bird in its own
    palette, clear where no bird is; the header tiles it and scales it up
    with nearest-neighbour."""
    grid, _, _ = wire.strip()
    pixels = [[(0, 0, 0, 0) if c is None else hexrgb(c) + (255,) for c in row] for row in grid]
    path = os.path.join(ROOT, "assets", "img", "pixel", "perch.png")
    write_png_rgba(path, len(grid[0]), len(grid), pixels)
    return path


def build_masks():
    lines = [
        "// Generated by _pixel/build.py — edit _pixel/sprites.py, not this file.",
        "// One-tone pixel sprites, used as CSS masks and coloured by the theme tokens.",
        "",
    ]
    for name, rows in all_masks().items():
        doc, w, h = svg(rows)
        uri = "data:image/svg+xml," + quote(doc, safe=" /:='.,-")
        lines.append("$px-%s: url(\"%s\");" % (name, uri))
        lines.append("$px-%s-w: %d;" % (name, w))
        lines.append("$px-%s-h: %d;" % (name, h))
    grid, _, below = wire.strip()
    lines += [
        "",
        "// The wire strip (assets/img/pixel/perch.png, _pixel/wire.py)",
        "$perch-w: %d;" % len(grid[0]),
        "$perch-h: %d;" % len(grid),
        "$perch-below: %d;  // rows under the wire, where tails hang" % below,
    ]
    path = os.path.join(ROOT, "_sass", "pixel", "_sprites.scss")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def build_cover(width=224):
    """Print the book cover in the paper's three inks, error-diffused at two
    print dots per CSS pixel (shown at 112 px wide), so the title stays
    legible. The lightest greys are lifted first so the cover's thin line art
    survives. Paper is left transparent."""
    src = os.path.join(ROOT, "_pixel", "src", "book-cover.jpg")
    if not (os.path.exists(src) and shutil.which("magick")):
        return None
    out = os.path.join(ROOT, "assets", "img", "pixel", "book-cover.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        palette = os.path.join(tmp, "inks.png")
        subprocess.run(["magick", "-size", "1x1"] +
                       ["xc:%s" % c for c in PRINT_TONES + [PAPER]] +
                       ["+append", palette], check=True)
        subprocess.run(
            ["magick", src, "-colorspace", "Gray", "-resize", "%dx" % width,
             "-level", "0%,97%,0.3", "-unsharp", "0x0.8+1.0+0", "-colorspace", "sRGB",
             "-dither", "FloydSteinberg", "-remap", palette,
             "-transparent", PAPER, "-strip", out],
            check=True)
    return out


if __name__ == "__main__":
    print("\n".join(build_pictures()))
    print(build_perch())
    print(build_masks())
    print(build_cover())
